### ISSUE TITLE
Cannot installed through pip

### ISSUE THREAD

**Issue by MuMuuuu** [orisano/owiener#2]
1.0.8 version cannot be installed through `python3 -m pip install owiener`
Need to git clone and run `sudo python3 setup.py install`

**Comment by orisano** [comment]
I need more information.
cannot reproduce...

**Comment by gdonald** [comment]
I did `python3 -m pip install owiener`, no errors.

But then when I do `import owiener` I get `ModuleNotFoundError: No module named 'owiener'`.
